- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - homebrew
    - homebrew-cask
    - ricty
    - ghq
  vars:
    # Tap external Homebrew repositories.
    #
    # e.g.
    # - homebrew/binary
    homebrew_repositories:
      - peco/peco

    # Managed Homebrew packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
    # install_options: string or sequence (default: none)
    homebrew_packages:
      - readline
      - openssl
      - { name: openssl, state: linked, install_options: force }
      - ansible
      - git
      - git-flow
      - heroku-toolbelt
      - peco
      - nvm
      - rbenv
      - rbenv-gem-rehash
      - ruby-build
      - the_silver_searcher
      - vim
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - ack
      - binutils
      - autoconf
      - gnu-sed
      - mysql
      - postgresql
      - w3m
      - wget
      - awscli
      - go
      - tmux
      - lv
      - ag
      - peco
      - pwgen
      - imagemagick
      - qt4  # capybara-webkit


    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions
      - dictav/splhack

    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - firefox-ja
      - flash
      - google-chrome
      - google-japanese-ime
      - iterm2
      - java6
      - karabiner
      - slack
      - sublime-text
      - vagrant
      - virtualbox
      - limechat
      - dropbox
      - xld
      - skitch
      - sourcetree
      - evernote
      - steam
      - boot2docker
      - dash
      - google-cloud-sdk


